# .readthedocs.yaml
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  commands:
    # Install Pixi using asdf (the same approach as uw-ssec/rse-guidelines)
    - asdf plugin add pixi
    - asdf install pixi latest
    - asdf global pixi latest

    # Run the Pixi task defined in pixi.toml that builds docs for RTD
    - NO_COLOR=1 pixi run rtd-publish
