# OVRO-LWA Portal Project Configuration
#
# This pixi.toml file manages dependencies and environments for the OVRO-LWA Portal,
# a Python library for radio astronomy data processing and visualization

[workspace]
# Project metadata and basic configuration
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]  # Primary conda channel for dependencies
name = "ovro-lwa-portal"
platforms = ["osx-arm64", "linux-64"]  # Supported platforms for development and deployment
version = "0.1.0"

# Environment definitions combining different feature sets
[environments]
# Default development environment with code quality tools
default = {features = ["pre-commit"]}
# Onboarding environment with SSEC-specific tools and setup utilities
onboarding = { features = ["pre-commit", "onboarding"] }

# Global tasks available across all environments
[tasks]

# Core dependencies for radio astronomy data processing
[dependencies]
python = "==3.12"
astropy = ">=7.1.0,<8"
xarray = ">=2025.9.1,<2026"
dask = ">=2025.9.1,<2026"
netcdf4 = ">=1.7.2,<2"
zarr = ">=3.1.3,<4"
numcodecs = ">=0.16.1,<0.17"

# Python packages not available in conda-forge
[pypi-dependencies]
# OVRO-LWA specific image plane correction algorithms
# Repository: https://github.com/ovro-lwa/image-plane-correction/tree/nikita/dev
image-plane-correction = { git = "https://github.com/ovro-lwa/image-plane-correction.git", branch = "nikita/dev"}

# Platform-specific dependencies for macOS ARM64
[target.osx-arm64.pypi-dependencies]
# BDSF (Blob Detection and Source Finder) - radio astronomy source finding
# Pre-compiled wheel for Apple Silicon to avoid compilation issues for MacOS 14+
bdsf = {url = "https://files.pythonhosted.org/packages/20/7f/bfd3a4788dd5400cec20d09f83c4d10e7ac486af807c90471917a28afa12/bdsf-1.13.0.post2-cp312-cp312-macosx_14_0_arm64.whl"}

# Code quality and development tools feature
[feature.pre-commit.dependencies]
pre-commit = ">=4.3.0"

# SSEC-specific onboarding and project setup tools
[feature.onboarding.tasks]
# Pre-commit hook management tasks
pre-commit-install = { cmd = "pre-commit install", description = "Install pre-commit hooks for automatic code quality checks" }
pre-commit-all = { cmd = "pre-commit run --all-files", description = "Run all pre-commit hooks on entire codebase" }
pre-commit = { cmd = "pre-commit run", description = "Run pre-commit hooks on staged files" }

# Main onboarding task with dependencies
onboard = { cmd = "ssec onboard", description = "Complete SSEC project onboarding setup including tools and compliance", depends-on = ["pre-commit-install", "ssec-setup"] }

# SSEC CLI setup tasks
ssec-setup = { cmd = "ssec --install-completion", description = "Install SSEC CLI bash/zsh completion" }

# SSEC-specific tools for project management and compliance
[feature.onboarding.pypi-dependencies]
ssec-cli = { git = "https://github.com/uw-ssec/ssec-cli.git" }  # SSEC project management and onboarding tools
