[workspace]
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]
name = "ovro-lwa-portal"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[environments]
default = {features = ["pre-commit"]}
onboarding = { features = ["pre-commit", "onboarding"] }

[tasks]

[dependencies]
python = "==3.12"
astropy = ">=7.1.0,<8"
xarray = ">=2025.9.1,<2026"
dask = ">=2025.9.1,<2026"
netcdf4 = ">=1.7.2,<2"
zarr = ">=3.1.3,<4"
numcodecs = ">=0.16.1,<0.17"

[pypi-dependencies]
# https://github.com/ovro-lwa/image-plane-correction/tree/nikita/dev
image-plane-correction = { git = "https://github.com/lsetiawan/image-plane-correction.git", branch = "lsetiawan/dev"}

[target.osx-arm64.pypi-dependencies]
bdsf = {url = "https://files.pythonhosted.org/packages/20/7f/bfd3a4788dd5400cec20d09f83c4d10e7ac486af807c90471917a28afa12/bdsf-1.13.0.post2-cp312-cp312-macosx_14_0_arm64.whl"}


[feature.pre-commit.dependencies]
pre-commit = ">=4.3.0"

# Project Onboarding Dependencies
[feature.onboarding.tasks]
# pre-commit tasks
pre-commit-install = "pre-commit install"
pre-commit-all = "pre-commit run --all-files"
pre-commit = "pre-commit run"

onboard = { cmd = "ssec onboard", depends-on = [
    "pre-commit-install",
    "ssec-setup",
] }

# ssec-cli tasks
ssec-setup = "ssec --install-completion"

[feature.onboarding.pypi-dependencies]
ssec-cli = { git = "https://github.com/uw-ssec/ssec-cli.git" }
